version: '3'

services:
  container:
    image: game-of-life:latest
    deploy:
      replicas: 8
    networks:
      - mpi_net

networks:
  mpi_net:
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/8